# -*- coding: utf-8 -*-
"""Visualizer Linear System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psDQMAndkT8G8qDriFM6KMK1SOs8utXl
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Definisikan data
x = np.linspace(-10, 10, 1000)
y1 = 2 * x + 1
y2 = 3 * x - 5

# 2. Inisialisasi Plot (Penting agar 'ax' terdefinisi)
fig, ax = plt.subplots()

# 3. Tambahkan Garis Persamaan
ax.plot(x, y1, c='green', label='y = 2x + 1')
ax.plot(x, y2, c='brown', label='y = 3x - 5')

# 4. Bagian yang Sebelumnya Error
# Pastikan nilai limit sumbu cukup besar untuk melihat titik (6, 13)
ax.set_xlim([0, 10])
ax.set_ylim([0, 20])

# Menandai titik potong (6, 13)
plt.axvline(x=6, color='purple', linestyle='--')
plt.axhline(y=13, color='purple', linestyle='--')

plt.legend()
plt.show()